__title__ = "Autoscan"
__author__ = "by275"
__url__ = "https://github.com/by275/plex_autoscan"
__description__ = "Script to assist in scanning Plex library more efficiently."
__version__ = "0.1.0-DEV"
__license__ = "GNU General Public License v3.0"

__original_title__ = "Plex Autoscan"
__original_author__ = "l3uddz"
__original_url__ = "https://github.com/l3uddz/plex_autoscan"
